// SPDX-License-Identifier: AGPL-3.0-only
"use client";

import { ArrowLeft, CheckCircle2, Copy, FilePlus2, Fingerprint, ShieldAlert } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { formatScriptTimestamp, scriptState, type OperatorRole, type ScriptItem } from "@/lib/script-library-core";

export function ScriptDetailView({ initialScript, latestContent, role }: { initialScript: ScriptItem; latestContent: string; role: OperatorRole }) {
  const router = useRouter(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [showVersion, setShowVersion] = useState(false);
  const state = scriptState(initialScript); const latest = initialScript.latest;
  async function mutate(path: string, payload: unknown) { setBusy(true); setError(""); try { const response = await fetch(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "The change was not confirmed."); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "The change was not confirmed."); } finally { setBusy(false); } }
  async function addVersion(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await mutate(`/api/scripts/${encodeURIComponent(initialScript.id)}/versions`, { language: data.get("language"), content: data.get("content"), description: data.get("description") || undefined, tags: String(data.get("tags") ?? "").split(",").map((v) => v.trim()).filter(Boolean), supported_platforms: data.getAll("platform") }); }
  async function review(decision: "approved" | "rejected") { const reason = window.prompt(`${decision === "approved" ? "Approval" : "Rejection"} reason (stored as digest evidence):`); if (!reason) return; await mutate(`/api/scripts/${encodeURIComponent(initialScript.id)}/versions/${latest.version}/review`, { state: decision, reason }); }
  async function deprecate() { const reason = window.prompt("Deprecation reason (this action is permanent):"); if (!reason) return; await mutate(`/api/scripts/${encodeURIComponent(initialScript.id)}/deprecate`, { expected_record_version: initialScript.record_version, request_id: crypto.randomUUID(), reason }); }
  return <>
    <Link className="script-back" href="/scripts"><ArrowLeft size={15} />Back to library</Link>
    <header className="script-detail-head"><div><span>Stable script identity</span><h1>{initialScript.name}</h1><p>{latest.description ?? "No description provided."}</p></div><span className={`script-state ${state}`}>{state}</span></header>
    <section className="script-digest-rail"><div><small>Canonical content</small><strong>{latest.content_bytes.toLocaleString()} bytes</strong></div><i>→</i><div><small>SHA-256</small><code>{latest.content_sha256}</code></div><i>→</i><div><small>Review state</small><strong>{latest.review?.state ?? "Draft"}</strong></div></section>
    {error ? <p className="script-action-error" role="alert">{error}</p> : null}
    <div className="script-detail-grid"><section className="script-source-panel"><header><div><span>Latest immutable source</span><h2>Version {latest.version}</h2></div><button type="button" onClick={() => navigator.clipboard.writeText(latestContent)}><Copy size={15} />Copy</button></header><pre><code>{latestContent}</code></pre><footer><span>{latest.language}</span><span>{latest.supported_platforms.join(" · ")}</span><span>by {latest.created_by}</span></footer></section>
      <aside className="script-control-panel"><span>Workflow controls</span><h2>Custody actions</h2><p>Creating and reviewing library entries does not authorize endpoint execution.</p>
        {role !== "readonly" && !initialScript.deprecated_at ? <button onClick={() => setShowVersion((value) => !value)}><FilePlus2 size={16} />Create new version</button> : null}
        {role === "admin" && !latest.review && !initialScript.deprecated_at ? <><button className="approve" disabled={busy} onClick={() => review("approved")}><CheckCircle2 size={16} />Approve v{latest.version}</button><button className="reject" disabled={busy} onClick={() => review("rejected")}><ShieldAlert size={16} />Reject v{latest.version}</button></> : null}
        {role === "admin" && !initialScript.deprecated_at ? <button className="deprecate" disabled={busy} onClick={deprecate}>Deprecate permanently</button> : null}
        {role === "readonly" ? <small>Readonly operators may inspect content and evidence only.</small> : null}</aside></div>
    {showVersion ? <form className="script-create-panel" onSubmit={addVersion}><header><span>Append-only revision</span><h2>Create version {initialScript.latest_version + 1}</h2></header><div className="script-form-grid"><label>Language<select name="language" defaultValue={latest.language}><option value="powershell">PowerShell</option><option value="shell">POSIX shell</option></select></label><label>Tags<input name="tags" defaultValue={latest.tags.join(", ")} /></label><label className="wide">Description<input name="description" maxLength={2000} defaultValue={latest.description ?? ""} /></label><fieldset><legend>Supported platforms</legend>{["windows", "linux", "macos"].map((platform) => <label key={platform}><input type="checkbox" name="platform" value={platform} defaultChecked={latest.supported_platforms.includes(platform as never)} />{platform}</label>)}</fieldset><label className="wide">New content<textarea name="content" required rows={10} maxLength={57344} defaultValue={latestContent} spellCheck={false} /></label></div><footer><button type="button" onClick={() => setShowVersion(false)}>Cancel</button><button disabled={busy} type="submit">{busy ? "Saving…" : "Append immutable version"}</button></footer></form> : null}
    <section className="script-version-ledger"><header><div><Fingerprint size={18} /><span>Version ledger</span></div><small>Newest first · content never overwritten</small></header><div>{initialScript.versions?.map((version) => <article key={version.id}><span>v{version.version}</span><div><strong>{version.description ?? "No description"}</strong><small>{version.language} · {version.content_bytes.toLocaleString()} bytes · {formatScriptTimestamp(version.created_at)}</small></div><code>{version.content_sha256}</code><span className={`script-state ${version.review?.state ?? "draft"}`}>{version.review?.state ?? "draft"}</span></article>)}</div></section>
  </>;
}
